name: Build and Deploy Angular App to GCS

on:
  push:
    branches:
      - master
          
env:
  BRANCH_NAME: ${{ github.ref#refs/heads/ }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['development', 'staging', 'prod']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Generate Environment
        run: npm run generate-env:${{ matrix.env }}
        
      - name: Build Angular app
        run: ng build --configuration=${{ matrix.env }} --output-path=dist/ --base-href /angular_bucket_${{ matrix.env }}/

      - name: Authenticate with Google Cloud
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json

      - name: Deploy to GCS 
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gsutil -m cp -r dist/* gs://angular_bucket_${{ matrix.env }}
    if: env.BRANCH_NAME == matrix.env
