name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Convert env to uppercase
        id: convert
        run: |
          echo "::set-output name=ENV_UPPER::$(echo development | tr '[:lower:]' '[:upper:]')"

      - name: Generate Environment
        run: npm run generate-env:development
        env:
          TITLE: ${{ vars[format('{0}_TITLE', steps.convert.outputs.ENV_UPPER)] }}
          IFRAME: ${{ vars[format('{0}_IFRAME', steps.convert.outputs.ENV_UPPER)] }}

      - name: Run Linting
        run: npm run lint

      - name: Run Tests
        run: ng test --watch=false --browsers=ChromeHeadless

      - name: Set PR status - Success
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.repos.createStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              description: 'Linting and tests passed!',
              context: 'PR Checks'
            });
